language: scala

env:
  global:
    - secure: "nPtepdKPvidwnxijiaIQiKnwuNvy+P4YAQUe4+1UzsiNMLILC/8UgWlUHoJMmlcS9ycYM5G1EwQNiT3hJetJbRL4VN3/uhnNpntmucASpC1KbpGjl3gaMfx7yDnJj252aj0yrSDoxJHDXe9p7zBY+bV+Dvp/SWGO1216ZgpiEx+T2n7QJ7kj5dhU+j6AIPj2R1U2lGOiAjHaCudGlv7evswSYrfdXL9yRZGXxeM361vien1akwTjSJzZr/EZmXhVyBSEWKitWMLuboCmXaUvr+VZVm5FkY8X7FKKBre05/itWGQTrnrEaKaUMd1bW+GfPOyFTjmuJnLiwmSmeEx2o/krQt9EfyFJpSfiX/b5bxYQan+ozxiwrsDF0/7tYfGBVg48miccqN+oAtAD1X8cWYa9svLOwKnv82ELq/18QE5OY9DPc9zARGDnPxwZ96Zl6dDtQkJz2+qBo/EU8dU2q1uaNTvuImmtLAHQZ2PtzdaGkklQQ3YvfZeWyD/fTVZdMQi2NXv0LRHkwAxf65vwrf84Edyy+HlqD5zTpKzhr1q6+wj54oOsQDnK6gSmmguG5Nd2HbJQxQhDlEZQ6+b00TY5WxYPG5Qo5zH0TXbu+/txLZlZOyJ5qJqGCICC1QW3YNDvFbTBIYGQUKVZ6vadXD8SqFUNvYK/wXXLYmdoXm8="

jobs:
  include:
    - stage: unit-test
      before_script:
      - cd node-support && npm install && cd -
      - cd samples/js-shopping-cart && npm install && cd -
      script:
      - cd node-support && npm test && cd -
      - cd samples/js-shopping-cart && npm test && cd -
    - before_script:
      - sbt update
      script:
      - sbt 'set concurrentRestrictions in Global += Tags.limitAll(1)' test docs/paradox
    - stage: tck
      before_script:
      - sbt update
      - cd node-support && npm install && cd -
      - cd samples/js-shopping-cart && npm install && cd -
      script:
          - sbt 'set concurrentRestrictions in Global += Tags.limitAll(1)' tck/it:test
    - stage: deploy
      script: sbt docs/paradox
      deploy:
        provider: pages
        github_token: $GITHUB_TOKEN
        local_dir: docs/target/paradox/site/main
        repo: cloudstateio/docs
        target_branch: master
        keep_history: true
        email: deploy@cloudstate.io
        name: CloudState Deployment Bot

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.npm

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
